### ISSUE TITLE
Add website option as part of profile URLs 

### ISSUE THREAD

**Issue by nunoveloso** [marzeelabs/portuguese_women_tech#37]
From Liliana:

> Na secção das redes sociais de cada perfil, é possível incluir a possibilidade de site próprio, para além de social media?

**Comment by lmcorreia** [comment]
With an icon? Just ask @pdsdesign 

I can also jump in right after, turn the now string field into a select box for ease of use as discussed before

**Comment by pdsdesign** [comment]
Yep, with an icon should be fine to maintain the consistency with the rest
I'll get to it
