### ISSUE TITLE
design adjustment

### ISSUE THREAD

**Issue by lilianapncastro** [marzeelabs/portuguese_women_tech#46]
@pdsdesign can you update the twitter cover? right now it's too big and it's eating part of the text - sorry! just needs to go a bit to the left so we don't loose any info. thank you. cc/ @porto-io

**Comment by pdsdesign** [comment]
Hi @lilianapncastro , don't know how much is need to move, sending it but not sure if it is enough.
![tw_cover_img_white](https://cloud.githubusercontent.com/assets/17990934/24042833/aa9216da-0b0b-11e7-886a-2841f18d490c.png)
![tw_cover_img2](https://cloud.githubusercontent.com/assets/17990934/24042832/aa91b7ee-0b0b-11e7-8c30-afaeeb94b334.png)

**Comment by lilianapncastro** [comment]
@pdsdesign it's perfect now! thank you :)
