### ISSUE TITLE
Front page is loading large images

### ISSUE THREAD

**Issue by nunoveloso** [marzeelabs/portuguese_women_tech#71]
The front page images is loading the `-large` version.
This affects SEO and performance.

**Comment by Quicksaver** [comment]
Cache issues (technically a feature). From the moment Chrome has the -large image cached, that's the one it fetches regardless of what would be better suited for that page size. (Works as expected in Firefox.)

I believe this is already the best behavior. Performance will always be better when using cached images, if both ```-large``` and any other sizes are already available in cache, fetching either should make no practical difference; it's basically a [why not?](https://developers.google.com/web/ilt/pwa/lab-responsive-images#32_add_width_descriptors_to_the_srcset) approach.

As for SEO, I think that follows through. If analyzing browser performance on that page it'll know that the browser is fetching the absolute best resource (preferring cached); if analyzing the page itself directly, it will (or should) know how to read and use the ```srcset``` and its listed images properly (i.e. with and without cache).

How wrong am I?

**Comment by jolidog** [comment]
@Quicksaver @nunoveloso The image sizes are wrong none the less, and the sizes/srcs need tweaks. I'll review today.
